name = "HeatEquation"
uuid = "e6e20fc8-a3f9-45de-8b8c-0a58e0f5fede"
version = "1.0.0-DEV"
authors = ["Takis Angelides"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
GraphViz = "f526b714-d49f-11e8-06ff-31ed36ee7ee0"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
BenchmarkTools = "1.6.3"
GraphViz = "0.2.0"
PProf = "3.2.0"
Plots = "1.41.2"
Profile = "1.11.0"
ProgressMeter = "1.11.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
