name = "HeatEquation"
uuid = "e6e20fc8-a3f9-45de-8b8c-0a58e0f5fede"
version = "1.0.0-DEV"
authors = ["Takis Angelides"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
ParallelStencil = "94395366-693c-11ea-3b26-d9b7aac5d958"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[compat]
BenchmarkTools = "1.6.3"
Distributed = "1.11.0"
Metal = "1.9.1"
ParallelStencil = "0.14.3"
Plots = "1.41.2"
ProgressMeter = "1.11.0"
SharedArrays = "1.11.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
